drop table if exists post CASCADE;

create table post
(
    id              bigint generated by default as identity,
    author          varchar(10) not null,
    password        varchar(10),
    side            varchar(5),
    relationship    varchar(10),
    content         varchar(255) not null,
    likes           int,
    primary key (id)
);

drop table if exists likes CASCADE;

create table likes
(
    id  bigint generated by default as identity,
    address varchar(40),
    post_id bigint,
    primary key (id),
    foreign key (post_id) references post(id)
);